### ISSUE TITLE
Minor issues building Daikon with Dockerfile

### ISSUE THREAD

**Issue by VHellendoorn** [melonhead901/daikon-dot-net-front-end#114]
Using one of the provided Docker image (specifically, `Dockerfile-ubuntu-jdk8`) to recompile Daikon (in my case, rebuild the Daikon Jar), I ran into two small issues that may not necessarily be bugs (hence no PR) but may be worth inspecting:

1. Line 57 of java/Makefile sets the `-Werror` flag. This causes the program to exit in case of compile warnings; since there are about 47 such warnings (many for seemingly insignificant issues), I had to remove this flag to allow full compilation.
2. The build script relies on the rsync package, which is not included in the Dockerfile.

I can send a PR fixing either/both of the above, but figured I'd first check if/to what extent these are design decisions

**Comment by kellend-git** [comment]
Hi Vincent,

Thanks for the comment, however I believe you might have intended to file this on the daikon repository (https://github.com/codespecs/daikon) and not on this one for the .NET front-end. It sounds like these errors should be fixed, so I encourage you to file this issue there.

--Kellen

**Comment by VHellendoorn** [comment]
You are absolutely right, my bad!
